r"""Select the MES + MOO subset of the Tier A bibliography.

The full review now narrows its scope to surrogate models for
multi-objective optimization of multi-energy systems, i.e.\ the
intersection of three filter dimensions that the screening CSV already
records:

- Tier A           (explicit surrogate term + ESM context)
- ESM term         contains a multi-energy / sector-coupling cue
- OPT term         contains a multi-objective / Pareto cue

The script reads ``surrogates_esm_screening_enriched.csv``, copies the
matching rows into ``surrogates_esm_mes_moo.csv``, extracts the same
keys from ``surrogates_esm.bib`` into ``surrogates_esm_mes_moo.bib``,
and prints summary counts so it is obvious whether the subset is large
enough to support a review.

Usage::

    python select_mes_moo_subset.py
"""

from __future__ import annotations

import argparse
import csv
import re
import sys
from collections import Counter
from pathlib import Path
from typing import Dict, Iterable, List, Set


# Keep the term lists tight: we want a clear signal that the paper is
# about an MES / multi-energy problem AND about MOO. Generic
# ``multi-energy load forecasting`` would still match on the ESM side
# but should be filtered out at the OPT side because it does not have
# any MOO term.
MES_HINTS = (
    "multi-energy",
    "multi energy",
    "integrated energy",
    "sector coupling",
    "energy hub",
    "virtual power plant",
)

# Microgrids and energy communities are extremely common host systems
# for surrogate-assisted MOO and are therefore included in the MES
# umbrella for this review, in line with the user's existing draft.
MICROGRID_HINTS = (
    "microgrid",
    "energy community",
    "energy communities",
    "energy planning",
)

MOO_HINTS = (
    "multi-objective",
    "multi objective",
    "pareto",
)


def matches(bag: str, hints: Iterable[str]) -> bool:
    return any(h in bag for h in hints)


def load_csv(path: Path) -> List[Dict[str, str]]:
    with path.open(encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def write_csv(rows: List[Dict[str, str]], path: Path, fieldnames: List[str]) -> None:
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


# ---------------------------------------------------------------------------
# Bib slicing
#
# We do not re-parse the bib. We just scan it once with a regex that matches
# ``@TYPE{key,`` and walk forward with a brace counter so we can extract
# each block verbatim. That keeps the formatting Scopus produced.
# ---------------------------------------------------------------------------


def slice_bib(bib_path: Path, keep_keys: Set[str], out_path: Path) -> int:
    text = bib_path.read_text(encoding="utf-8")
    starts = [m.start() for m in re.finditer(r"@\w+\s*\{", text)]
    starts.append(len(text))

    blocks: List[str] = []
    for start, next_start in zip(starts[:-1], starts[1:]):
        open_brace = text.find("{", start)
        if open_brace == -1:
            continue
        depth = 1
        i = open_brace + 1
        while i < len(text) and depth > 0:
            ch = text[i]
            if ch == "{":
                depth += 1
            elif ch == "}":
                depth -= 1
            i += 1
        if depth != 0:
            continue
        close_idx = i - 1
        body = text[open_brace + 1:close_idx]
        comma_idx = body.find(",")
        if comma_idx == -1:
            continue
        key = body[:comma_idx].strip()
        if key in keep_keys:
            blocks.append(text[start:close_idx + 1])

    with out_path.open("w", encoding="utf-8") as f:
        f.write("% Generated by select_mes_moo_subset.py from surrogates_esm.bib.\n")
        f.write("% Do not edit by hand: the file is regenerated whenever\n")
        f.write("% the focus subset is re-derived.\n\n")
        for block in blocks:
            f.write(block)
            f.write("\n\n")
    return len(blocks)


def main(argv: List[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--csv-in",
        type=Path,
        default=Path("surrogates_esm_screening_enriched.csv"),
    )
    parser.add_argument(
        "--bib-in",
        type=Path,
        default=Path("surrogates_esm.bib"),
    )
    parser.add_argument(
        "--csv-out",
        type=Path,
        default=Path("surrogates_esm_mes_moo.csv"),
    )
    parser.add_argument(
        "--bib-out",
        type=Path,
        default=Path("surrogates_esm_mes_moo.bib"),
    )
    parser.add_argument(
        "--include-microgrid",
        action="store_true",
        default=True,
        help="include microgrid / energy-community papers in the MES umbrella (default)",
    )
    parser.add_argument(
        "--strict-mes",
        dest="include_microgrid",
        action="store_false",
        help="exclude microgrid / energy-community papers (only true MES / sector-coupling hits)",
    )
    args = parser.parse_args(argv)

    rows = load_csv(args.csv_in)
    print(f"Loaded {len(rows)} rows from {args.csv_in}")

    mes_or_micro = MES_HINTS + (MICROGRID_HINTS if args.include_microgrid else ())
    print(f"MES vocabulary ({len(mes_or_micro)} terms): {mes_or_micro}")
    print(f"MOO vocabulary ({len(MOO_HINTS)} terms): {MOO_HINTS}")
    print()

    n_a = 0
    n_a_mes = 0
    n_a_moo = 0
    keep: List[Dict[str, str]] = []
    for r in rows:
        if r.get("tier") != "A":
            continue
        n_a += 1
        esm_bag = (r.get("matched_esm_terms") or "").lower()
        opt_bag = (r.get("matched_opt_terms") or "").lower()
        is_mes = matches(esm_bag, mes_or_micro)
        is_moo = matches(opt_bag, MOO_HINTS)
        if is_mes:
            n_a_mes += 1
        if is_moo:
            n_a_moo += 1
        if is_mes and is_moo:
            keep.append(r)

    print(f"Tier A total                  : {n_a}")
    print(f"Tier A & MES context          : {n_a_mes}")
    print(f"Tier A & MOO context          : {n_a_moo}")
    print(f"Tier A & MES & MOO (kept)     : {len(keep)}")
    print()

    fieldnames = list(rows[0].keys()) if rows else []
    write_csv(keep, args.csv_out, fieldnames)
    print(f"Wrote {args.csv_out}")

    n_blocks = slice_bib(args.bib_in, set(r["cite_key"] for r in keep), args.bib_out)
    print(f"Wrote {args.bib_out} with {n_blocks} bib entries")
    print()

    print("Top primary topics in the MES x MOO subset:")
    topics = Counter((r.get("primary_topic") or "(none)") for r in keep)
    for t, n in topics.most_common(15):
        print(f"  {n:4d}  {t}")
    print()

    print("Read-priority distribution in the kept subset:")
    rp = Counter((r.get("read_priority") or "(none)") for r in keep)
    for k, n in rp.most_common():
        print(f"  {k:<10} {n}")

    print()
    print("Top 10 most-cited entries in the MES x MOO subset:")
    sorted_by_cit = sorted(
        (r for r in keep if (r.get("cited_by_count") or "").strip()),
        key=lambda r: int(r["cited_by_count"]),
        reverse=True,
    )[:10]
    for r in sorted_by_cit:
        print(f"  cit={r['cited_by_count']:>5}  oa={r['oa_status']:<8}  {r['cite_key']:<25}  {r['title'][:80]}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
