from __future__ import annotations
from dataclasses import dataclass
from dataclasses import field
from typing import List, Optional

@dataclass
class ReportingConfig:
    auto_report: bool = True
    write_csv: bool = True
    # Controls heavy hourly time-series CSV export independently from pareto_points.csv.
    write_timeseries: bool = True
    timeseries_max_points: Optional[int] = 5
    write_plot: bool = True
    write_summary: bool = True
    plot_max_points: Optional[int] = None
    output_root: str = "Optimization/run/results"
    write_dispatch_kpis: bool = True
    write_thermflex_hourly: bool = False
    dispatch_kpis_json_filename: str = "dispatch_kpis.json"
    dispatch_kpis_csv_filename: str = "dispatch_kpis.csv"
    thermflex_hourly_csv_filename: str = "thermflex_hourly.csv"
    dispatch_kpi_names: List[str] = field(default_factory=lambda: [
        "thermal_archetype_variant",
        "dispatch_objective_eur",
        "dispatch_operating_cost_eur",
        "dispatch_penalty_total_eur",
        "dispatch_cost_eur",
        "grid_import_cost_eur",
        "grid_export_revenue_eur",
        "fuel_cost_eur",
        "co2_cost_eur",
        "variable_opex_eur",
        "unserved_penalty_eur",
        "temperature_violation_penalty_eur",
        "thermflex_activation_penalty_eur",
        "spill_penalty_eur",
        "co2_emissions_total_t",
        "district_gas_boiler_co2_t",
        "district_gas_chp_co2_t",
        "district_gas_boiler_generation_kwh",
        "district_gas_boiler_peak_kw",
        "district_gas_chp_thermal_generation_kwh",
        "district_gas_chp_electric_generation_kwh",
        "district_heat_pump_generation_kwh",
        "district_external_heat_generation_kwh",
        "district_waste_incineration_generation_kwh",
        "dh_unserved_heat_kwh",
        "thermflex_shifted_space_heat_kwh",
        "thermflex_additional_space_heat_kwh",
        "thermflex_rebound_kwh",
        "thermflex_peak_change_kw",
        "dh_total_peak_change_kw",
        "thermflex_heat_up_ramp_kw_per_h",
        "thermflex_heat_down_ramp_kw_per_h",
        "thermflex_effective_thermal_storage_kwh",
        "thermflex_max_preheat_headroom_kwh",
        "thermflex_active_member_hours_total",
        "thermflex_temperature_violation_degree_hours_total",
        "thermflex_t_in_min_c",
        "thermflex_t_in_max_c",
        "thermflex_t_in_terminal_c",
        "thermflex_use_explicit_lower_bounds",
        "thermflex_constant_lower_bound_c",
        "thermflex_day_lower_bound_c",
        "thermflex_night_lower_bound_c",
        "thermflex_constrain_upper_temperature",
        "thermflex_max_flex_duration_h",
        "thermflex_max_events_per_day",
        "thermflex_event_response_bounds_active",
        "thermflex_event_peak_bounds_active",
        "thermflex_event_energy_bounds_active",
        "thermflex_event_recovery_cooldown_active",
        "thermflex_preheat_event_energy_limit_kwh_total",
        "thermflex_cutback_event_energy_limit_kwh_total",
        "thermflex_recovery_rebound_energy_kwh_total",
        "thermflex_recovery_time_to_reference_h_mean",
        "thermflex_recovery_time_to_reference_h_max",
        "thermflex_preheat_peak_excess_kwh_per_step_max",
        "thermflex_cutback_peak_shed_kwh_per_step_max",
        "thermflex_event_preheat_extra_realized_kwh",
        "thermflex_event_cutback_shed_realized_kwh",
    ])
    dispatch_kpi_normalization_windows_h: List[int] = field(default_factory=lambda: [24, 168, 8760])


def make_reporting() -> ReportingConfig:
    return ReportingConfig(
        auto_report=True,
        write_csv=True,
        write_timeseries=True,
        timeseries_max_points=5,
        write_plot=True,
        write_summary=True,
        plot_max_points=None,
        output_root="Optimization/run/results",
        write_dispatch_kpis=True,
        write_thermflex_hourly=False,
        dispatch_kpis_json_filename="dispatch_kpis.json",
        dispatch_kpis_csv_filename="dispatch_kpis.csv",
        thermflex_hourly_csv_filename="thermflex_hourly.csv",
        dispatch_kpi_names=[
            "thermal_archetype_variant",
            "dispatch_objective_eur",
            "dispatch_operating_cost_eur",
            "dispatch_penalty_total_eur",
            "dispatch_cost_eur",
            "grid_import_cost_eur",
            "grid_export_revenue_eur",
            "fuel_cost_eur",
            "co2_cost_eur",
            "variable_opex_eur",
            "unserved_penalty_eur",
            "temperature_violation_penalty_eur",
            "thermflex_activation_penalty_eur",
            "spill_penalty_eur",
            "co2_emissions_total_t",
            "district_gas_boiler_co2_t",
            "district_gas_chp_co2_t",
            "district_gas_boiler_generation_kwh",
            "district_gas_boiler_peak_kw",
            "district_gas_chp_thermal_generation_kwh",
            "district_gas_chp_electric_generation_kwh",
            "district_heat_pump_generation_kwh",
            "district_external_heat_generation_kwh",
            "district_waste_incineration_generation_kwh",
            "dh_unserved_heat_kwh",
            "thermflex_shifted_space_heat_kwh",
            "thermflex_additional_space_heat_kwh",
            "thermflex_rebound_kwh",
            "thermflex_peak_change_kw",
            "dh_total_peak_change_kw",
            "thermflex_heat_up_ramp_kw_per_h",
            "thermflex_heat_down_ramp_kw_per_h",
            "thermflex_effective_thermal_storage_kwh",
            "thermflex_max_preheat_headroom_kwh",
            "thermflex_active_member_hours_total",
            "thermflex_temperature_violation_degree_hours_total",
            "thermflex_t_in_min_c",
            "thermflex_t_in_max_c",
            "thermflex_t_in_terminal_c",
            "thermflex_use_explicit_lower_bounds",
            "thermflex_constant_lower_bound_c",
            "thermflex_day_lower_bound_c",
            "thermflex_night_lower_bound_c",
            "thermflex_constrain_upper_temperature",
            "thermflex_max_flex_duration_h",
            "thermflex_max_events_per_day",
            "thermflex_event_response_bounds_active",
            "thermflex_event_peak_bounds_active",
            "thermflex_event_energy_bounds_active",
            "thermflex_event_recovery_cooldown_active",
            "thermflex_preheat_event_energy_limit_kwh_total",
            "thermflex_cutback_event_energy_limit_kwh_total",
            "thermflex_recovery_rebound_energy_kwh_total",
            "thermflex_recovery_time_to_reference_h_mean",
            "thermflex_recovery_time_to_reference_h_max",
            "thermflex_preheat_peak_excess_kwh_per_step_max",
            "thermflex_cutback_peak_shed_kwh_per_step_max",
            "thermflex_event_preheat_extra_realized_kwh",
            "thermflex_event_cutback_shed_realized_kwh",
        ],
        dispatch_kpi_normalization_windows_h=[24, 168, 8760],
    )
